/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Alan Godinez
 */
public class TablaDeSimbolos extends javax.swing.JPanel {

    /**
     * Creates new form TablaDeSimbolos
     */
    public TablaDeSimbolos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Si	", "Palabra reservada para condición en una estructura de control if "},
                {"SINO", "Palabra reservada para condición alternativa en un if "},
                {"FinSino", "Palabra reservada que marca el final de una condición alternativa en una estructura de control if "},
                {"FinSi", "Palabra reservada que marca el final de una estructura de control if "},
                {"Repite", "Palabra reservada para iniciar un bucle de repetición "},
                {"Mientras", "Palabra reservada para iniciar un bucle while "},
                {"FMientras", "Palabra reservada que marca el final de un bucle while "},
                {"Car", "Palabra reservada para tipo de dato de caracteres "},
                {"Cad", "Palabra reservada para tipo de dato de cadenas de caracteres "},
                {"Num", "Palabra reservada para tipo de dato de números enteros "},
                {"IniC	", "Palabra reservada para iniciar un bloque de código "},
                {"FinC", "Palabra reservada que marca el final de un bloque de código "},
                {"IniB", "Palabra reservada para iniciar un bloque "},
                {"FinB", "Palabra reservada que marca el final de un bloque "},
                {"Dec", "Palabra reservada para tipo de dato de números decimales "},
                {"Bool", "Palabra reservada para tipo de dato de valores booleanos "},
                {"Seno", "Palabra reservada para la función trigonométrica seno "},
                {"Coseno", "Palabra reservada para la función trigonométrica coseno "},
                {"Tangente", "Palabra reservada para la función trigonométrica tangente "},
                {"Cotangente", "Palabra reservada para la función trigonométrica cotangente "},
                {"Secante", "Palabra reservada para la función trigonométrica secante "},
                {"Cosecante", "Palabra reservada para la función trigonométrica cosecante "},
                {"Elegir", "Palabra reservada para iniciar una estructura de control switch/case "},
                {"Com", "Palabra reservada para comunicación "},
                {"MensajeS", "Palabra reservada para mostrar mensajes "},
                {"DatoE", "Palabra reservada para entrada de datos "},
                {"Posicion", "Palabra reservada para la posición "},
                {"Gravedad", "Palabra reservada para constante especial de la gravedad "},
                {"Sprite", "Palabra reservada para manipular sprites "},
                {"Velocidad", "Palabra reservada para la velocidad "},
                {"Vacio", "Palabra reservada para un valor vacío o nulo     "}
            },
            new String [] {
                "Palabras Reservas", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
