// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: C:/Users/ar90w/OneDrive/Documentos/GitHub/Compilador_LyA/src/Jflex/AnalisisLexico.flex

import java.io.*;


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int IN_STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\5\u0100\1\u0200\1\u0300\1\u0100\5\u0400\1\u0500\1\u0600"+
    "\1\u0700\6\u0100\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00"+
    "\3\u0100\1\u0e00\205\u0100\1\u0600\1\u0100\1\u0f00\1\u1000\1\u1100"+
    "\1\u1200\54\u0100\10\u1300\37\u0100\1\u0900\4\u0100\1\u1400\10\u0100"+
    "\1\u1500\2\u0100\1\u1600\1\u1700\1\u1200\1\u0100\1\u0500\1\u0100"+
    "\1\u1800\1\u1500\1\u0800\3\u0100\1\u1100\1\u1900\114\u0100\1\u1a00"+
    "\1\u1100\153\u0100\1\u1b00\11\u0100\1\u1c00\1\u1200\6\u0100\1\u1100"+
    "\u0f16\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\2\0\2\1\24\0\1\2\2\0\1\3"+
    "\4\0\1\3\1\4\1\0\1\4\1\5\1\3\12\6"+
    "\3\0\1\7\3\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\10\1\17\3\10\1\20\1\21\1\10"+
    "\1\22\1\10\1\23\1\24\1\25\1\10\1\26\4\10"+
    "\1\0\1\27\2\0\1\10\1\0\1\30\1\10\1\31"+
    "\1\32\1\33\1\10\1\34\1\10\1\35\1\36\1\10"+
    "\1\37\1\40\1\41\1\42\1\43\1\10\1\44\1\45"+
    "\1\46\1\47\1\50\4\10\u01e5\0\12\51\206\0\12\51"+
    "\306\0\12\51\234\0\12\51\166\0\12\51\140\0\12\51"+
    "\166\0\12\51\106\0\12\51\u0116\0\12\51\106\0\12\51"+
    "\u0146\0\12\51\46\0\12\51\u012c\0\12\51\200\0\12\51"+
    "\246\0\12\51\6\0\12\51\266\0\12\51\126\0\12\51"+
    "\206\0\12\51\6\0\12\51\u0276\0\12\51\46\0\12\51"+
    "\306\0\12\51\26\0\12\51\126\0\12\51\u0196\0\12\51"+
    "\u01a6\0\12\51\206\0\12\51\u012c\0\12\51\200\0\12\51"+
    "\74\0\12\51\220\0\12\51\166\0\12\51\146\0\12\51"+
    "\206\0\12\51\106\0\12\51\266\0\12\51\u0164\0\62\51"+
    "\100\0\12\51\266\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[7424];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\1\1\2\1\1\2\3\1\1\1\4\1\5\17\6"+
    "\1\7\1\1\1\4\1\1\20\6\1\10\4\6\1\7"+
    "\1\1\1\4\1\6\1\10\33\6\1\10\16\6";

  private static int [] zzUnpackAction() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\52\0\250\0\322\0\374"+
    "\0\52\0\u0126\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222"+
    "\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348\0\u0372"+
    "\0\52\0\u039c\0\u03c6\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498"+
    "\0\u04c2\0\u04ec\0\u0516\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8"+
    "\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4\0\u070e\0\u0738"+
    "\0\u0762\0\176\0\u078c\0\u078c\0\u07b6\0\u0126\0\u07e0\0\u080a"+
    "\0\u0834\0\u085e\0\u0888\0\u08b2\0\u08dc\0\u0906\0\u0930\0\u095a"+
    "\0\u0984\0\u09ae\0\u09d8\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa"+
    "\0\u0ad4\0\u0afe\0\u0b28\0\u0b52\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa"+
    "\0\u0c24\0\u0c4e\0\u0c78\0\u0ca2\0\u0ccc\0\u0cf6\0\u0d20\0\u0d4a"+
    "\0\u0d74\0\u0d9e\0\u0dc8\0\u0df2\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\2"+
    "\21\12\1\10\53\2\1\3\50\2\2\4\1\31\24\4"+
    "\1\32\22\4\5\2\1\7\1\10\42\2\1\10\6\2"+
    "\1\33\42\2\1\33\5\2\1\7\1\10\5\2\1\34"+
    "\16\2\1\34\15\2\1\10\6\2\1\12\1\2\17\12"+
    "\1\2\21\12\7\2\1\12\1\2\17\12\1\2\12\12"+
    "\1\35\6\12\7\2\1\12\1\2\17\12\1\2\1\36"+
    "\11\12\1\37\6\12\7\2\1\12\1\2\17\12\1\2"+
    "\1\40\2\12\1\41\15\12\7\2\1\12\1\2\17\12"+
    "\1\2\7\12\1\42\11\12\7\2\1\12\1\2\10\12"+
    "\1\43\6\12\1\2\5\12\1\44\13\12\7\2\1\12"+
    "\1\2\17\12\1\2\14\12\1\45\4\12\7\2\1\12"+
    "\1\2\17\12\1\2\11\12\1\46\7\12\7\2\1\12"+
    "\1\2\17\12\1\2\3\12\1\47\1\12\1\50\13\12"+
    "\7\2\1\12\1\2\17\12\1\2\17\12\1\51\1\12"+
    "\7\2\1\12\1\2\17\12\1\2\12\12\1\52\6\12"+
    "\7\2\1\12\1\2\17\12\1\2\3\12\1\53\15\12"+
    "\7\2\1\12\1\2\17\12\1\2\3\12\1\54\1\12"+
    "\1\55\5\12\1\56\5\12\7\2\1\12\1\2\17\12"+
    "\1\2\1\57\20\12\7\2\1\12\1\2\17\12\1\2"+
    "\1\60\2\12\1\61\15\12\1\2\2\4\1\62\24\4"+
    "\1\32\22\4\6\2\1\33\5\2\1\34\16\2\1\34"+
    "\15\2\1\33\4\2\1\63\1\2\1\64\42\2\1\64"+
    "\6\2\1\12\1\2\17\12\1\2\12\12\1\65\6\12"+
    "\7\2\1\12\1\2\17\12\1\2\2\12\1\66\11\12"+
    "\1\66\4\12\7\2\1\12\1\2\17\12\1\2\10\12"+
    "\1\66\4\12\1\67\1\27\2\12\7\2\1\12\1\2"+
    "\17\12\1\2\16\12\1\70\2\12\7\2\1\12\1\2"+
    "\17\12\1\2\1\12\1\66\17\12\7\2\1\12\1\2"+
    "\17\12\1\2\3\12\1\71\15\12\7\2\1\12\1\2"+
    "\17\12\1\2\5\12\1\50\13\12\7\2\1\12\1\2"+
    "\17\12\1\2\11\12\1\72\7\12\7\2\1\12\1\2"+
    "\17\12\1\2\1\73\20\12\7\2\1\12\1\2\17\12"+
    "\1\2\5\12\1\74\13\12\7\2\1\12\1\2\17\12"+
    "\1\2\11\12\1\75\7\12\7\2\1\12\1\2\17\12"+
    "\1\2\3\12\1\76\15\12\7\2\1\12\1\2\17\12"+
    "\1\2\10\12\1\66\10\12\7\2\1\12\1\2\17\12"+
    "\1\2\15\12\1\77\3\12\7\2\1\12\1\2\17\12"+
    "\1\2\13\12\1\100\5\12\7\2\1\12\1\2\17\12"+
    "\1\2\1\12\1\101\7\12\1\102\7\12\7\2\1\12"+
    "\1\2\11\12\1\102\5\12\1\2\21\12\7\2\1\12"+
    "\1\2\17\12\1\2\14\12\1\100\4\12\7\2\1\12"+
    "\1\2\17\12\1\2\11\12\1\103\7\12\7\2\1\12"+
    "\1\2\17\12\1\2\1\12\1\104\17\12\7\2\1\12"+
    "\1\2\17\12\1\2\7\12\1\105\11\12\7\2\1\64"+
    "\42\2\1\64\6\2\1\12\1\2\17\12\1\2\7\12"+
    "\1\66\11\12\7\2\1\12\1\2\17\12\1\2\3\12"+
    "\1\54\15\12\7\2\1\12\1\2\17\12\1\2\12\12"+
    "\1\106\6\12\7\2\1\12\1\2\17\12\1\2\4\12"+
    "\1\107\14\12\7\2\1\12\1\2\1\12\2\66\11\12"+
    "\1\110\2\12\1\2\21\12\7\2\1\12\1\2\17\12"+
    "\1\2\20\12\1\111\7\2\1\12\1\2\1\12\2\66"+
    "\14\12\1\2\21\12\7\2\1\12\1\2\17\12\1\2"+
    "\15\12\1\112\3\12\7\2\1\12\1\2\17\12\1\2"+
    "\11\12\1\113\7\12\7\2\1\12\1\2\17\12\1\2"+
    "\5\12\1\114\13\12\7\2\1\12\1\2\17\12\1\2"+
    "\5\12\1\115\13\12\7\2\1\12\1\2\17\12\1\2"+
    "\1\116\20\12\7\2\1\12\1\2\17\12\1\2\12\12"+
    "\1\66\6\12\7\2\1\12\1\2\17\12\1\2\4\12"+
    "\1\117\14\12\7\2\1\12\1\2\17\12\1\2\5\12"+
    "\1\102\13\12\7\2\1\12\1\2\17\12\1\2\12\12"+
    "\1\120\6\12\7\2\1\12\1\2\4\12\1\66\12\12"+
    "\1\2\21\12\7\2\1\12\1\2\17\12\1\2\5\12"+
    "\1\121\13\12\7\2\1\12\1\2\17\12\1\2\5\12"+
    "\1\122\13\12\7\2\1\12\1\2\17\12\1\2\3\12"+
    "\1\123\15\12\7\2\1\12\1\2\17\12\1\2\1\124"+
    "\20\12\7\2\1\12\1\2\17\12\1\2\16\12\1\125"+
    "\2\12\7\2\1\12\1\2\17\12\1\2\1\12\1\126"+
    "\17\12\7\2\1\12\1\2\17\12\1\2\16\12\1\127"+
    "\2\12\7\2\1\12\1\2\17\12\1\2\11\12\1\115"+
    "\7\12\7\2\1\12\1\2\17\12\1\2\3\12\1\116"+
    "\15\12\7\2\1\12\1\2\17\12\1\2\1\12\1\130"+
    "\17\12\7\2\1\12\1\2\17\12\1\2\14\12\1\66"+
    "\4\12\7\2\1\12\1\2\17\12\1\2\11\12\1\102"+
    "\7\12\7\2\1\12\1\2\17\12\1\2\2\12\1\131"+
    "\16\12\7\2\1\12\1\2\17\12\1\2\6\12\1\132"+
    "\12\12\7\2\1\12\1\2\17\12\1\2\14\12\1\133"+
    "\4\12\7\2\1\12\1\2\17\12\1\2\5\12\1\134"+
    "\13\12\7\2\1\12\1\2\17\12\1\2\3\12\1\66"+
    "\15\12\7\2\1\12\1\2\17\12\1\2\5\12\1\123"+
    "\13\12\7\2\1\12\1\2\17\12\1\2\1\135\20\12"+
    "\7\2\1\12\1\2\17\12\1\2\3\12\1\136\15\12"+
    "\7\2\1\12\1\2\17\12\1\2\1\137\20\12\7\2"+
    "\1\12\1\2\17\12\1\2\12\12\1\140\6\12\7\2"+
    "\1\12\1\2\17\12\1\2\2\12\1\66\16\12\7\2"+
    "\1\12\1\2\14\12\1\66\2\12\1\2\21\12\7\2"+
    "\1\12\1\2\17\12\1\2\15\12\1\66\3\12\7\2"+
    "\1\12\1\2\17\12\1\2\11\12\1\66\7\12\1\2";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3780];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\140\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
    zzAtEOF = true;
    return new Token(sym.EOF, "EOF");
}

      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Token(sym.OPERADORRE, yytext());
            }
          // fall through
          case 9: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 10: break;
          case 3:
            { return new Token(sym.OPERADORAR, yytext());
            }
          // fall through
          case 11: break;
          case 4:
            { return new Token(sym.NUMERO, yytext());
            }
          // fall through
          case 12: break;
          case 5:
            { return new Token(sym.OPERADORASG, yytext());
            }
          // fall through
          case 13: break;
          case 6:
            { return new Token(sym.IDENTIFICADOR, yytext());
            }
          // fall through
          case 14: break;
          case 7:
            { return new Token(sym.CARACTER, yytext());
            }
          // fall through
          case 15: break;
          case 8:
            { return new Token(sym.PALABRARESERVADA, yytext());
            }
          // fall through
          case 16: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   */
  private static String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as yylex but also prints the token to standard out
   * for debugging.
   */
 
  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        java.io.FileInputStream stream = null;
        java.io.Reader reader = null;
        try {
          stream = new java.io.FileInputStream(argv[i]);
          reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
        finally {
          if (reader != null) {
            try {
              reader.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
          if (stream != null) {
            try {
              stream.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
        }
      }
    }
  }


}
